[world]
name = "Nums"
seed = "nums-v1.0.60"
description = "On chain version of the Number Challenge or Blind Number Challenge game."
website = "https://nums.gg"

[namespace]
default = "NUMS"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
world_address = "0xa71ca11a93851d12746627c16a07f52d3324e8d8d36b04da6c959fd5e932d7"
account_address = "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753"
keystore_path = "./keystore_sepolia.json"

[migration]
order_inits = [
  "NUMS-Token",
  "NUMS-Setup",
  "NUMS-Play",
  "NUMS-Collection",
  "NUMS-Vault",
  "NUMS-Faucet",
]
skip_contracts = ["NUMS-Vrf"]
disable_multicall = true

[writers]
"NUMS" = ["NUMS-Setup", "NUMS-Play"]

[owners]
"NUMS" = ["NUMS-Collection", "NUMS-Vault", "NUMS-Faucet", "NUMS-Token"]

[init_call_args]
"NUMS-Vault" = [
  "0x1", # open: true
  "0x0", # fee: 500 basis points (10000 basis points = 100%)
]
"NUMS-Governor" = []
"NUMS-Treasury" = [
  "0xe10",                                                              # min_delay: 1 hour
  "0x0000000000000000000000000000000000000000000000000000000000000000", # Admin address
]
"NUMS-Token" = [
  "0xD3C21BCECCEDA1000000",                                             # initial_supply: 1.0M NUMS
  "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753", # recipient
]
"NUMS-Faucet" = [
  "0x2540BE400",                                                        # initial_supply: 10K USDC
  "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753", # recipient
]
"NUMS-Setup" = [
  "0x0",                                                                # Option::Some
  "0x051fea4450da9d6aee758bdeba88b2f665bcbf549d2c61421aa724e9ac0ced8f", # vrf_address
  "0x1",                                                                # quote_address: None
  "0x059b1a0c489b635d7c7f43594d187362ddd2dcea6c82db4eef2579fd185b3753", # team_address
  "0x050d4da9f66589eadaa1d5e31cf73b08ac1a67c8b4dcd88e6fd4fe501c628af2", # ekubo router address
  "0x06a2aee84bb0ed5dded4384ddd0e40e9c1372b818668375ab8e3ec08807417e5", # ekubo positions address
  "0x1E8480",                                                           # entry_price: 2.000000 USDC
  "0xD3C21BCECCEDA1000000",                                             # target_supply: 1M NUMS
  "0x46",                                                               # burn_percentage: 70%,
  "0x32",                                                               # vault_percentage: 50%,
  "0xA",                                                                # average_score: 10,
  "0xccccccccccccccccccccccccccccccc",                                  # pool_fee,
  "0x56a4c",                                                            # pool_tick_spacing,
  "0x073ec792c33b52d5f96940c2860d512b3884f2127d25e023eb9d44a678e4b971", # pool_extension,
  "0x005974abf73ca39b2c71a5e9459590f50649e53b296e747d2fc414bbd8839aab", # bundle_allower
]
